### PR TITLE
feat: using flags as defualts in interactive mode

### PR DESCRIPTION
**Pull request by mtsitrin**
when initiailizng a rollapp, the default config is read from the existing rollapp config

# PR Standards

## Opening a pull request should be able to meet the following requirements

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

**Review by ItayLevyOfficial — COMMENTED** [review]
So the defaults are the values of the currently existed rollapp if it exists? Isn't this weird? don't we want to have a consistent defaults

**Comment by mtsitrin** [comment]
> So the defaults are the values of the currently existed rollapp if it exists? Isn't this weird? don't we want to have a consistent defaults

thought about it
we can do either.
IMO, if u have existing roller instance, u could take the values from it as a default

if u think otherwise, for non-interactive mode, it's easy to change

**Comment by ItayLevyOfficial** [comment]
ye let's keep the defaults constant for now; If a user run init again his current config may be fucked, we don't neccassirily want to use it as default

**Comment by ItayLevyOfficial** [comment]
why only if non interactive? 🤔

**Review by ItayLevyOfficial — APPROVED** [review]
LGTM!

**Pull request merged**
